In [1]:
import datetime
from zoneinfo import ZoneInfo
# from pathlib import Path
import pathlib

import numpy as np
import subprocess
import os
import getpass


import morph_analyses as m


%load_ext autoreload
%autoreload 2

In [2]:
mouse = m.mouse_metadata.rare_mice[0]
metadata = m.mouse_metadata.rare_sessions[mouse]
session = metadata['test_sessions'][0]

In [3]:
session

{'date_str': '19_02_2019',
 'scene': 'TwoTower_foraging',
 'session': 2,
 'scan': 2,
 'day': 8,
 'datetime': datetime.datetime(2019, 2, 19, 0, 0)}

In [14]:
nwb_maker = m.create_nwb.SessNWBConverter(mouse, metadata, session, training_session=False)

In [15]:
nwb_maker.sess.place_cell_info

{'masks': {0.0: array([ True,  True, False, ..., False, False, False], shape=(1828,)),
  0.25: array([ True,  True, False, ..., False, False, False], shape=(1828,)),
  0.5: array([False, False, False, ..., False, False, False], shape=(1828,)),
  0.75: array([False, False, False, ..., False, False, False], shape=(1828,)),
  1.0: array([False, False, False, ..., False, False, False], shape=(1828,))},
 'SI': {0.0: array([0.29396534, 1.38749294, 0.44955743, ..., 0.08915176, 0.15140964,
         0.27277584], shape=(1828,)),
  0.25: array([0.32102271, 1.61539835, 0.46066511, ..., 0.13570547, 0.24441911,
         0.23803949], shape=(1828,)),
  0.5: array([0.21186992, 0.26192756, 0.23602277, ..., 0.22185178, 0.28020366,
         0.32582006], shape=(1828,)),
  0.75: array([0.31628711, 0.13900611, 0.3276315 , ..., 0.28194697, 0.10407893,
         0.35284339], shape=(1828,)),
  1.0: array([0.04610355, 0.15870286, 0.23677114, ..., 0.06472743, 0.17158686,
         0.27051641], shape=(1828,))},
 'p': {0.0: array([0.007, 0.001, 0.56 , ..., 0.799, 0.491, 0.11 ], shape=(1828,)),
  0.25: array([0.043, 0.022, 0.8  , ..., 0.87 , 0.242, 0.32 ], shape=(1828,)),
  0.5: array([0.337, 0.177, 0.993, ..., 0.232, 0.103, 0.129], shape=(1828,)),
  0.75: array([0.127, 0.723, 0.74 , ..., 0.207, 0.959, 0.142], shape=(1828,)),
  1.0: array([0.953, 0.278, 0.669, ..., 0.893, 0.271, 0.055], shape=(1828,))}}

In [16]:
nwb_maker.build_file()

R1

/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/src/morph_analyses/create_nwb.py:294: FutureWarning: Images.__init__: Using positional arguments for this method is discouraged and will be deprecated in a future major release. Please use keyword arguments to ensure future compatibility.
  images = Images("Backgrounds", description='motion aligned average images')
/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/.venv/lib/python3.11/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'rois' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

In [17]:
nwb_maker.nwb_file

root pynwb.file.NWBFile at 0x140412651211408
Fields:
  acquisition: {
    trial_data <class 'pynwb.misc.AnnotationSeries'>
  }
  devices: {
    Microscope <class 'pynwb.device.Device'>
  }
  experiment_description: Testing session. Morph task.
  experimenter: ['Plitt, Mark']
  file_create_date: [datetime.datetime(2026, 4, 7, 23, 24, 22, 132964, tzinfo=tzlocal())]
  identifier: b9be7dc8-b0a0-42a6-b6c6-31efb15c0394
  imaging_planes: {
    ImagingPlane <class 'pynwb.ophys.ImagingPlane'>
  }
  institution: Stanford University
  keywords: ['two photon' 'hipppocampus' 'CA1' 'remapping']
  lab: Lisa Giocomo
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>,
    ophys <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['https://doi-org/10.1038/s41593-021-00816-6']
  session_description: Preprocessed 2P and VR Data
  session_id: testing_day8
  session_start_time: 2026-04-07 23:24:22.132712-07:00
  subject: subject pynwb.file.Subject at 0x140412649617680
Fields:
  age: P104D
  age__reference: birth
  description: Rare morph mouse
  genotype: CaMKII-Cre
  sex: M
  species: Mus musculus
  subject_id: R1

  timestamps_reference_time: 2026-04-07 23:24:22.132712-07:00

In [18]:
nwb_maker.write_file()