In [1]:
import datetime
from zoneinfo import ZoneInfo
# from pathlib import Path
import pathlib

import numpy as np
import subprocess
import os
import getpass


import morph_analyses as m


%load_ext autoreload
%autoreload 2

In [23]:
mouse = m.mouse_metadata.rare_mice[4]
metadata = m.mouse_metadata.rare_sessions[mouse]
session = metadata['test_sessions'][-1]

In [24]:
mouse

'R5'

In [25]:
session

{'date_str': '22_03_2020',
 'scene': 'TwoTower_foraging',
 'session': 2,
 'scan': 2,
 'day': 9,
 'datetime': datetime.datetime(2020, 3, 22, 0, 0)}

In [26]:
nwb_maker = m.create_nwb.SessNWBConverter(mouse, metadata, session, training_session=False)

In [27]:
nwb_maker.build_file()

4343703.1

/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/src/morph_analyses/create_nwb.py:291: FutureWarning: Images.__init__: Using positional arguments for this method is discouraged and will be deprecated in a future major release. Please use keyword arguments to ensure future compatibility.
  images = Images("Backgrounds", description='motion aligned average images')
/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/.venv/lib/python3.11/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'rois' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

In [28]:
nwb_maker.nwb_file

root pynwb.file.NWBFile at 0x140206185662288
Fields:
  acquisition: {
    trial_data <class 'pynwb.misc.AnnotationSeries'>
  }
  devices: {
    Microscope <class 'pynwb.device.Device'>
  }
  experiment_description: Testing session. Morph task.
  experimenter: ['Plitt, Mark']
  file_create_date: [datetime.datetime(2026, 4, 13, 15, 47, 24, 459954, tzinfo=tzlocal())]
  identifier: 41d1472e-33b6-4013-9171-f0bac72eccba
  imaging_planes: {
    ImagingPlane <class 'pynwb.ophys.ImagingPlane'>
  }
  institution: Stanford University
  keywords: ['two photon' 'hipppocampus' 'CA1' 'remapping']
  lab: Lisa Giocomo
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>,
    ophys <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['https://doi-org/10.1038/s41593-021-00816-6']
  session_description: Preprocessed 2P and VR Data
  session_id: testing_day9
  session_start_time: 2026-04-13 15:47:24.459439-07:00
  subject: subject pynwb.file.Subject at 0x140206127549136
Fields:
  age: P145D
  age__reference: birth
  description: Rare morph mouse
  genotype: CaMKII-Cre
  sex: M
  species: Mus musculus
  subject_id: R5

  timestamps_reference_time: 2026-04-13 15:47:24.459439-07:00

In [29]:
nwb_maker.write_file()