In [1]:
import datetime
from zoneinfo import ZoneInfo
# from pathlib import Path
import pathlib

import numpy as np
import subprocess
import os
import getpass


import morph_analyses as m


%load_ext autoreload
%autoreload 2

In [3]:
mouse = m.mouse_metadata.frequent_mice[0]
metadata = m.mouse_metadata.frequent_sessions[mouse]
session = metadata['test_sessions'][0]

In [4]:
session

{'date_str': '15_04_2019',
 'scene': 'TwoTower_foraging',
 'session': 2,
 'scan': 3,
 'day': 8,
 'datetime': datetime.datetime(2019, 4, 15, 0, 0)}

In [5]:
nwb_maker = m.create_nwb.SessNWBConverter(mouse, metadata, session, training_session=False)

In [6]:
nwb_maker.sess.place_cell_info

{'masks': {0.0: array([False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True, False, False,  True,
         False, False, False, False, False, False, False, False, False,
         False, False,  True, False, False,  True, False,  True, False,
         False, False, False, False, False, False,  True, False, False,
         False, False,  True, False,  True, False, False, False, False,
         False, False,  True, False, False, False,  True, False, False,
         False,  True, False, False, False,  True,  True, False,  True,
         False, False, False, False,  True, False, False,  True, False,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False,  True, False, False, False,  True,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False, False, False, False, False,
          True,  True,  True, False, False, False, False, False, False,
         False, False, False,  True,  True, False,  True, False, False,
         False, False, False, False,  True, False, False, False, False,
          True, False, False, False, False, False,  True, False, False,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
          True,  True, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False,  True, False, False,
          True, False, False, False, False, False, False, False, False,
         False,  True, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True, False,  True,  True,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False,  True, False, False, False, False,
          True, False, False, False, False, False, False,  True,  True,
         False, False,  True, False, False, False,  True, False, False,
          True, False, False, False,  True, False,  True, False, False,
         False, False,  True, False, False, False, False, False, False,
         False, False, False, False]),
  0.25: array([False, False, False, False,  True, False, False, False, False,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True, False,  True,  True,
         False, False, False, False, False, False, False, False,  True,
          True, False,  True, False, False, False,  True,  True, False,
         False, False, False, False, False,  True, False, False, False,
          True, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
          True,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False, False, False, False, False, False,
          True, False, False, False, False, False,  True, False, False,
          True, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
         False, False, False, False,  True, False,  True,  True, False,
          True, False,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False,  True,
         False, False, False, False, False,  True, False, False, False,
         False, False, False,  True, False, False, False, False,  True,
         False, False, False, False, False, False,  True, False, False,
         False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False,  True, False, False, False,  True,
         False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False,  True, False, False, False, False,
          True, False, False, False, False, False, False,  True, False,
         False, False, False, False]),
  0.5: array([False, False, False, False,  True,  True, False, False, False,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False, False, False, False,  True,
         False,  True, False, False, False, False, False, False, False,
          True, False,  True, False, False, False, False,  True, False,
         False, False,  True,  True, False, False,  True, False, False,
          True,  True, False,  True,  True, False, False, False, False,
         False, False,  True,  True, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
          True, False, False, False,  True, False, False, False, False,
         False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True,  True,
         False, False, False,  True, False, False,  True, False, False,
          True, False, False, False, False, False, False,  True, False,
          True,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False,  True,
         False, False,  True, False,  True, False, False, False, False,
         False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False,  True,
         False, False, False, False,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False,  True, False, False, False,  True,  True, False,
         False,  True, False, False, False, False, False, False, False,
         False,  True, False, False, False, False, False, False,  True,
         False, False, False, False, False, False,  True, False, False,
         False, False, False, False,  True, False, False, False, False,
         False,  True, False, False, False, False, False, False, False,
         False, False, False, False]),
  0.75: array([False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False,  True, False, False, False,
         False,  True, False, False, False, False, False, False, False,
          True, False, False, False, False, False,  True,  True, False,
         False, False,  True, False, False, False,  True, False, False,
          True,  True,  True, False, False, False, False, False, False,
          True, False, False,  True, False,  True,  True, False, False,
         False, False, False, False,  True, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
          True,  True, False, False,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True,  True,
          True, False, False,  True, False, False,  True, False, False,
         False, False, False, False, False, False, False,  True,  True,
         False, False,  True, False,  True, False,  True, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
         False, False, False, False, False, False,  True, False, False,
         False, False, False, False, False,  True, False, False,  True,
         False, False, False, False, False, False, False, False, False,
         False,  True,  True, False,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False,  True, False, False, False, False,
         False, False, False, False, False, False,  True, False, False,
          True, False, False, False,  True, False, False, False, False,
         False,  True, False, False, False,  True, False, False, False,
         False, False,  True, False, False, False,  True,  True, False,
         False,  True, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False, False, False, False, False, False,
         False, False, False, False]),
  1.0: array([False, False, False, False,  True,  True, False, False, False,
         False, False, False, False, False,  True, False, False, False,
         False, False, False, False, False,  True, False, False,  True,
         False,  True, False, False, False, False,  True, False, False,
          True, False, False,  True, False, False,  True,  True, False,
         False, False,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False,  True,
         False, False, False, False,  True, False, False,  True, False,
          True,  True, False, False, False, False, False, False, False,
          True, False,  True, False,  True, False, False, False, False,
         False,  True, False, False,  True, False, False, False, False,
         False, False, False, False, False, False, False,  True,  True,
         False,  True,  True,  True, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False,
         False, False, False,  True, False, False, False, False, False,
         False, False, False,  True, False, False,  True, False, False,
         False, False,  True, False, False, False, False, False, False,
         False, False,  True, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
          True, False,  True, False,  True, False,  True, False, False,
          True,  True, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False,
          True, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False,  True, False, False, False, False,  True, False,  True,
          True,  True,  True, False, False, False, False, False,  True,
         False, False,  True, False,  True, False,  True, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False,  True, False, False, False, False, False, False,
          True, False, False, False])},
 'SI': {0.0: array([ 1.04436836e-01,  5.77073394e-02,  8.27396065e-02,  9.89118608e-02,
          2.29894891e-01,  7.04857478e-01,  6.91441186e-01,  4.56164603e-01,
          1.14040543e-01,  6.48130690e-01,  3.56684179e-01,  1.16092555e+00,
          4.64123335e-01,  3.18865352e-01,  1.88581337e+00,  1.18692224e-01,
          3.69269852e-01,  1.86704103e-01,  1.35578473e-01,  3.95723382e-01,
          1.37574054e-01, -2.57271056e-02,  5.13065057e-01,  1.50288181e+00,
          3.42655065e-02,  5.16068350e-01,  1.20896543e+00,  3.61313744e-01,
          1.75667955e-01,  1.89955784e-01,  2.10455504e-01,  2.20901987e-01,
          2.12731789e-01,  2.91388027e-01,  1.44390664e-01,  1.06298188e+00,
          6.62167002e-01,  5.21365271e-02,  9.53868282e-01,  4.30868667e-01,
          7.19569458e-02,  1.12554656e+00,  1.70878173e-02,  1.16949144e+00,
          3.43600420e-01,  3.51367908e-01,  2.32851963e-01,  1.99849674e-01,
          4.87394028e-02,  4.17991647e-01,  1.22538061e-01,  5.75440291e-01,
          2.72383164e-01,  3.15640591e-01,  2.42259833e-01,  4.04578319e-01,
          6.18074740e-01,  3.20938376e-01,  1.14384593e+00,  7.19347129e-02,
          2.02557295e-01,  4.36386671e-01,  9.72911037e-02,  6.53743775e-02,
          3.79721025e-02,  6.73456399e-01,  4.64697455e-01,  2.09912681e-01,
          4.12194371e-01,  1.44267995e+00,  2.68809805e-01,  2.77308487e-01,
          3.08721303e-01,  4.08376686e-01,  2.46463689e-01,  3.15350281e-01,
          2.44097591e-01,  1.08453022e+00,  9.26373922e-01,  2.20178728e-01,
          5.80432617e-01,  4.88013672e-01,  2.37169608e-01,  1.89449951e-02,
          8.87081543e-02,  1.43564187e+00,  1.88817326e-01,  3.15288680e-01,
          4.57662240e-01,  6.49882420e-01,  7.99759108e-02,  3.67150621e-01,
          1.57504891e-01,  1.76760334e-01,  2.24889182e-01,  9.09509042e-02,
          1.64517607e-01,  1.87394727e-01,  3.98806196e-01,  3.51439566e-01,
          2.51413588e+00,  4.39043682e-01,  1.90349877e-01,  9.90641273e-01,
          4.69949804e-02,  2.45160895e-01,  2.22964354e-01,  9.29306315e-01,
          2.79719422e-01,  1.40643105e-01,  1.44289805e-01,  3.30545037e-01,
          1.05374547e-01,  4.25175956e-01,  9.26419527e-02,  2.15697943e-01,
          2.18303505e-02,  1.53103788e-01,  3.73482410e-01,  3.11368206e-01,
          2.20217538e-01,  6.07344811e-01,  1.79396650e-01,  3.36890086e-01,
          3.45086617e-01,  1.11240595e-01,  7.75099073e-01,  5.72541213e-01,
          5.67975258e-01,  4.55087152e-01,  1.28990928e-01,  3.53579143e-01,
          5.08518894e-01,  2.93357565e-01,  1.37020483e-01,  3.92135332e-01,
          1.67336566e-01,  5.46005251e-01,  1.21401248e+00,  9.54521770e-01,
          1.74779895e-01,  1.87798358e+00,  1.48026492e-01,  6.57558370e-01,
          3.59012396e-01,  1.71270707e-01,  3.51337800e-01,  3.72081671e-01,
          4.65169791e-01,  3.44445460e-01,  2.32295370e-01,  1.81901658e-01,
          5.12958802e-02,  9.26006864e-01,  2.00641435e-01,  3.77119836e-01,
          1.54996493e-01,  4.05653862e-01,  1.74456468e-01,  5.82442678e-01,
          2.15387191e-01,  1.41649275e-01,  1.13388761e-01,  1.52386664e-01,
          1.39488664e-01,  8.42281705e-02,  2.63627765e-01,  1.48925729e+00,
          2.98739264e-01,  1.36609979e-01,  1.45760448e-01,  4.59986547e-01,
          1.69694827e-01,  2.15928899e-01,  5.29634456e-02,  4.52047569e-02,
          1.53272377e-01,  1.76102560e-01,  3.38107801e-01,  3.01089918e-01,
          3.08465221e-01,  8.93930189e-02,  9.93608153e-02,  1.55025005e-01,
          1.56069147e-01,  2.05823279e-01,  5.02495429e-01,  2.01652012e-01,
          7.98595304e-02,  4.72601338e-01,  5.28587495e-01,  1.32087803e-01,
          2.64071804e-01,  1.89790671e-01,  3.06332381e-01,  2.04514660e-01,
          1.41582188e+00,  1.13744180e-01,  1.15575493e-01,  1.60894594e-01,
          2.52889688e-01,  1.98523020e-01,  3.20825563e-01,  6.80461641e-02,
         -1.75315037e-03,  1.26068547e-01,  1.33694927e-01,  5.69045915e-02,
          3.03908682e-01,  2.17357032e-01,  1.19189998e+00,  3.69246274e-01,
          4.62836169e-02,  9.28615425e-01,  3.04477670e-01,  2.02653744e-01,
          4.47621828e-01,  7.31787044e-02,  2.80968734e-01,  1.50329689e-01,
          2.59102752e-01,  3.68829078e-03,  7.48819161e-02,  4.81679714e-02,
          3.44786612e-01,  1.46619004e-01,  6.19325001e-01,  1.85342384e-01,
          1.79712641e-01,  5.44556955e-02,  4.53391372e-01,  1.81579805e-01,
          3.29320147e-01,  2.32407595e-01,  1.72269826e-01,  1.45911286e-01,
          1.68931657e-01,  2.08321468e-01,  4.63180392e-01,  3.63715507e-01,
          2.54330936e-01,  4.48724389e-01,  3.90264054e-01,  1.20550122e-01,
          9.58268145e-02,  2.81206543e-01,  4.40188049e-01,  2.58143979e-01,
          3.74987527e-01,  1.08417878e-01,  1.41727112e-01,  1.67764882e-01,
          4.26033303e-01,  4.31725258e-02,  2.01736020e-01,  2.27029061e-02,
          7.14285841e-01,  8.93673728e-02,  2.34418111e-01,  5.28885615e-01,
          2.34702688e-01,  5.60782419e-01,  5.91644102e-02,  2.13051201e-01,
          1.84630263e-01,  1.39389116e-01,  1.89720359e-01,  1.41717049e-01,
          7.83882229e-01,  2.63141759e+00,  1.94541752e-01,  1.91846785e-01,
          6.66963040e-01,  4.72789666e-01,  1.41610387e-01,  6.78850281e-02,
          6.95925851e-01,  1.10183155e-01,  2.11591921e-01,  6.94206971e-01,
          2.14183735e-01,  9.46930000e-02,  1.13129874e-01,  3.86647936e-01,
          7.74654045e-02,  3.18203268e-01,  2.79184112e-01,  1.59509972e-01,
          1.24132191e-01,  2.14831594e-01,  6.70042665e-01,  1.36809056e-01,
          1.33533096e-01,  1.46074036e-01,  2.54967652e-01,  1.02607863e-01,
          1.57444862e-01,  2.13889061e-01,  6.90344991e-02,  2.52759965e-01,
          2.02808962e-01]),
  0.25: array([0.34067816, 0.0111937 , 0.18109295, 0.29075738, 0.77076246,
         0.27037582, 0.18305242, 0.09050545, 0.26320021, 0.53404686,
         0.24913606, 0.56824398, 0.54982841, 0.31836517, 0.90586665,
         0.46921565, 0.34954456, 0.14153951, 0.10745642, 0.40925643,
         0.12503608, 0.01180028, 0.22754294, 1.00359532, 0.435739  ,
         0.63247533, 1.06838464, 0.08764031, 0.41639378, 0.23572257,
         0.07068566, 0.18179565, 0.45625221, 0.04402881, 0.23352384,
         0.76857345, 1.01620032, 0.08364049, 1.08073201, 0.23257585,
         0.18187362, 0.30540454, 0.5723298 , 0.55033644, 0.58459996,
         0.3565567 , 0.30627297, 0.32754716, 0.2209588 , 0.27385698,
         0.56792744, 0.2186253 , 0.42204662, 0.16722345, 0.93545522,
         0.23594588, 0.33405717, 0.48811997, 0.29727974, 0.15980545,
         0.14771275, 0.17644586, 0.21199142, 0.20832232, 0.13443658,
         0.30705116, 0.68685538, 0.33144708, 0.58030185, 0.34501644,
         0.33313428, 0.24034988, 0.20580827, 0.30780648, 0.39664543,
         0.09753312, 0.11352056, 0.1923708 , 0.21799798, 0.27591249,
         0.18992746, 0.83752231, 0.53871948, 0.16218567, 0.17757472,
         0.37908067, 0.25243867, 0.19658633, 0.15297725, 0.11812791,
         0.16946446, 0.23671709, 0.17761643, 0.21896423, 0.30814482,
         0.13552656, 0.2658347 , 0.57279456, 0.21441802, 0.26191643,
         0.32609005, 0.3068125 , 0.10752301, 0.13070812, 0.13339239,
         0.18802968, 0.07434904, 0.5139502 , 0.08792202, 0.23381309,
         0.15729818, 0.17855995, 0.27843457, 0.52260262, 0.17620988,
         0.19381805, 0.1608586 , 0.12183133, 0.44737276, 0.206917  ,
         0.24589749, 0.42528877, 0.19998725, 0.28556014, 0.29595011,
         0.21082659, 0.52181248, 0.25392078, 0.23508985, 0.48137406,
         0.17249159, 0.19667105, 0.72043066, 0.22351566, 0.14804986,
         0.44908656, 0.24137259, 0.17995545, 0.35540591, 0.30234849,
         0.1222788 , 0.17288544, 0.1523706 , 0.22903528, 0.32666296,

In [7]:
nwb_maker.build_file()

F1

/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/src/morph_analyses/create_nwb.py:292: FutureWarning: Images.__init__: Using positional arguments for this method is discouraged and will be deprecated in a future major release. Please use keyword arguments to ensure future compatibility.
  images = Images("Backgrounds", description='motion aligned average images')
/home/mplitt/repos/PlittGiocomo_CA1Morph_2019/.venv/lib/python3.11/site-packages/hdmf/container.py:542: UserWarning: The linked table for DynamicTableRegion 'rois' does not share an ancestor with the DynamicTableRegion.
  child._validate_on_set_parent()

In [8]:
nwb_maker.nwb_file

root pynwb.file.NWBFile at 0x139944716556688
Fields:
  acquisition: {
    trial_data <class 'pynwb.misc.AnnotationSeries'>
  }
  devices: {
    Microscope <class 'pynwb.device.Device'>
  }
  experiment_description: Testing session. Morph task.
  experimenter: ['Plitt, Mark']
  file_create_date: [datetime.datetime(2026, 4, 8, 10, 52, 25, 136115, tzinfo=tzlocal())]
  identifier: cb2ed143-e793-47ee-bf8f-1c5fbbf743fe
  imaging_planes: {
    ImagingPlane <class 'pynwb.ophys.ImagingPlane'>
  }
  institution: Stanford University
  keywords: ['two photon' 'hipppocampus' 'CA1' 'remapping']
  lab: Lisa Giocomo
  processing: {
    behavior <class 'pynwb.base.ProcessingModule'>,
    ophys <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['https://doi-org/10.1038/s41593-021-00816-6']
  session_description: Preprocessed 2P and VR Data
  session_id: testing_day8
  session_start_time: 2026-04-08 10:52:25.135670-07:00
  subject: subject pynwb.file.Subject at 0x139944716401680
Fields:
  age: P88D
  age__reference: birth
  description: Frequent morph mouse
  genotype: CaMKII-Cre
  sex: M
  species: Mus musculus
  subject_id: F1

  timestamps_reference_time: 2026-04-08 10:52:25.135670-07:00

In [9]:
nwb_maker.write_file()